# Generated by Django 2.1.4 on 2019-01-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
